@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault

package amooooo.brewingoverhaul.blocks.crucible;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;